### ISSUE TITLE
Support Hald CLUTs

### ISSUE THREAD

**Issue by pflammertsma** [dntks/easyLUT#2]
It would be nice if easyLUT supported Hald variant color lookup tables.

There's a nice description with some C source code on this website:  
http://www.quelsolaar.com/technology/clut.html

The trouble is that the API will need to change, since Hald LUTs and regular LUTs are both square images; they only differ in grid sizes. Compare these two 512x512 images:

Conventional LUT:
![Regular LUT](https://user-images.githubusercontent.com/286051/33431017-01931d3e-d5d3-11e7-9aa0-d3a9a6ed6687.png)

Hald LUT:
![Hald LUT](https://user-images.githubusercontent.com/286051/33431037-23391b46-d5d3-11e7-9758-8d4f0980bc7c.png)

**Comment by pflammertsma** [comment]
Hald support and countless other improvements have been made in https://github.com/Pixplicity/easyLUT. Let me know if you want me to make a massive PR for all this.

**Comment by dntks** [comment]
Cool, thanks again for the contribution!
