### ISSUE TITLE
License

### ISSUE THREAD

**Issue by NoahRowlett** [dntks/easyLUT#5]
Hi, could you please add licensing information to your project? I'd like to use it for a project of mine, but can't unless I know how you want to license your repository.

**Comment by dntks** [comment]
Hi, I'd say it is Apache License, Version 2.0, but I can only add it next
week.
Also some fixes are not yet available through maven repo yet please beware
of that, or use a clone from latest master on github.

Best wishes,
Donat

**Comment by NoahRowlett** [comment]
Sounds good! If you could add it that would be great. Thanks!

**Comment by dntks** [comment]
Hi, I've added Apache license v2.0
